[package]
name = "ion"
version = "0.1.0"
authors = ["Justin Michaud <justin@justinmichaud.com>"]

[lib]
name = "ion"
path = "src/lib.rs"

[[bin]]
name = "ion_bin"
path = "src/main.rs"

[dependencies]
glutin = "0.12.0"
libservo = { path = "../servo/components/servo" }